<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620172154 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE race_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, points DOUBLE PRECISION NOT NULL, fastest_lap BOOLEAN NOT NULL, rider_id INT NOT NULL, race_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_793CDFC0FF881F6 ON race_result (rider_id)');
        $this->addSql('CREATE INDEX IDX_793CDFC06E59D40D ON race_result (race_id)');
        $this->addSql('ALTER TABLE race_result ADD CONSTRAINT FK_793CDFC0FF881F6 FOREIGN KEY (rider_id) REFERENCES rider (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE race_result ADD CONSTRAINT FK_793CDFC06E59D40D FOREIGN KEY (race_id) REFERENCES race (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE race_result DROP CONSTRAINT FK_793CDFC0FF881F6');
        $this->addSql('ALTER TABLE race_result DROP CONSTRAINT FK_793CDFC06E59D40D');
        $this->addSql('DROP TABLE race_result');
    }
}
